NAME = "Youtube"
SLUG = "youtube"
URL = "http://www.youtube.com"
DESCRIPTION = ""
TYPE = "video"

IMPLEMENTS_KEYWORDS_SEARCH  = True
IMPLEMENTS_USER_SEARCH  = True
IMPLEMENTS_LOCATION_SEARCH  = False
IMPLEMENTS_USER_ALBUMS  = False
