NAME = "Facebook"
SLUG = "facebook"
URL = "http://www.facebook.com"
DESCRIPTION = ""
TYPE = "photo"

IMPLEMENTS_KEYWORDS_SEARCH  = False
IMPLEMENTS_USER_SEARCH  = True
IMPLEMENTS_LOCATION_SEARCH  = False
IMPLEMENTS_USER_ALBUMS  = True