NAME = "Vimeo"
SLUG = "vimeo"
URL = "http://www.vimeo.com"
DESCRIPTION = ""
TYPE = "video"

IMPLEMENTS_KEYWORDS_SEARCH  = True
IMPLEMENTS_USER_SEARCH  = True
IMPLEMENTS_LOCATION_SEARCH  = False
IMPLEMENTS_USER_ALBUMS  = False
